### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Narrowism** [NikitaBuyevich/Gold-Quest#1]
So! This very early build of gold quest has great controls. Just wanted to ask a few questions.

When do you think you'll be done?
Are you doing this by yourself?
and
Whats the story of the game?

Thanks a bunch if you reply. Good luck! 

P.S.: If you are still working on this, I would love to help! (I make sprites, so if you need help with that, I can help.)

**Comment by nikitabuyevich** [comment]
Hi Narrowism,

Glad you like the little project. Currently it's a little bit in a hiatus as I am transitioning the engine from GM:S to Unity and I've been busy the past couple of months. As to answer your questions:

> When do you think you'll be done?

My goal is to finish by the time I graduate, so hopefully in two years. I'm not rushing or spending all of my free time on the project so I'm taking it slowly.

> Are you doing this by yourself?

I have an artist that I teamed up with that does all the pixel art, while I work on the development side of things.

> Whats the story of the game?

The story is developing but the general idea is that five golden items have been stolen from the kingdom and it's your chance to find them and return them.

> P.S.: If you are still working on this, I would love to help! (I make sprites, so if you need help with that, I can help.)

Sure, some help would be nice. [Send me an email](mailto:me@nikitabuyevich.com) of some of your art/portfolio so I can get a general sense of your skill.

Cheers.

**Comment by Narrowism** [comment]
Alright, thanks for replying!

Thank you and have a good day!
Alex P.

**Comment by Narrowism** [comment]
Alright, thanks for replying! (I also wanted to say that I usually am
better at drawing objects than characters)

Thank you and have a good day!
Alex P.

**Comment by Narrowism** [comment]
actually, is there a specific art style your going for or no? Just want to
make sure.

Thank you and have a good day!
Alex P.

**Comment by Narrowism** [comment]
here are some of some gifs I drew a while back: [image: Inline image 2][image:
Inline image 1]

Thank you and have a good day!
Alex P.
